Fix build issue related to Terraform plugin cache
When trying to build I get the following error from Terraform:

```
Error: Failed to install provider

Error while installing hashicorp/azurerm v2.85.0: after installing
registry.terraform.io/hashicorp/azurerm it is still not detected in the
target directory; this is a bug in Terraform
```

Removing TF_PLUGIN_CACHE_DIR fixes this, there must be some conflict
between the cache and the way bazel works, need to investigate further.