Fix providers config generation
When main.tf gets generated, some providers contain slashes (e.g.
akamai/akamai). This causes Terraform to complain:

```
Error: Argument or block definition required

On main.tf line 12: An argument or block definition is required here.
To set an argument, use the equals sign "=" to introduce the argument
value.
```

Update the awk files to handle the format Terraform now expects for
these types of providers.